### ISSUE TITLE
Issue getting summoner

### ISSUE THREAD

**Issue by dgraney** [BenFradet/RiotSharp#456]
I get an error of "One or more errors occurred" via the following:
`Summoner summoner = riotApi.GetSummoner(Region.na, "LeeSinSec");`

I somewhat assume this may be from #454, would this be a correct assumption?

**Comment by BenFradet** [comment]
Could you detail the "One or more errors occurred"?

**Comment by JanOuborny** [comment]
Can I assume that you are not using the latest build, Because the function `GetSummoner` got replaced with `GetSummonerByName`.

**Comment by dgraney** [comment]
Stack Trace:
```
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at RiotSharp.Requester.GetResult(HttpRequestMessage request)
   at RiotSharp.RateLimitedRequester.CreateGetRequest(String relativeUrl, Region region, List`1 addedArguments, Boolean useHttps)
   at RiotSharp.RiotApi.GetSummoner(Region region, String summonerName)
   at DiscordBot_Hearthstone.League.RankedStatsWithChamp_Registered(String champName, UInt64 userID) in C:\Users\GraneyD\Source\Repos\discord-bot\DiscordBot-Hearthstone\League.cs:line 37

```
Inner Exception Message: `The remote name could not be resolved: 'na.api.pvp.net'`

**Comment by JanOuborny** [comment]
The region domains are deprecated. You have to update to the latest build to use the new platform domains.

**Comment by dgraney** [comment]
Alright thank you very much!

**Comment by ikazimirs** [comment]
dgraney - did you manage to fix this? im getting the exact same error - i removed RiotSharp from references and installed the nuget package and i still dont have  GetSummonerByName

**Comment by dgraney** [comment]
ikazimirs - yes and no. 
Instead of using nugget, clone this repository, open the solution, and build it. Then grab the built .dll and throw it in with your current project. Then it's as simple as referencing the dll.

That being said, I ran into a weird dependency issue that I believe came as a conflict between this library and another. Right now I am just settling with using Champion.gg's API (which isn't nearly as complete as the official).

**Comment by JanOuborny** [comment]
@ikazimirs @dgraney To use the latest version of this project in a clean way, create a NuGet package of the latest version. See #445 for more information.
