### ISSUE TITLE
Error on GetSummoner()

### ISSUE THREAD

**Issue by Sking3000** [BenFradet/RiotSharp#463]
Hey,
Im using verison 2.5.6 of nuget

and i got an error while running this code:
` var api = RiotApi.GetInstance("API-KEY", 20, 100);
                var summoner = api.GetSummoner(RiotSharp.Region.eune, "sking3000");`

This is the Exception:

System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'eune.api.pvp.net'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task1.get_Result()
   at RiotSharp.Requester.GetResult(HttpRequestMessage request)
   at RiotSharp.RateLimitedRequester.CreateGetRequest(String relativeUrl, Region region, List`1 addedArguments, Boolean useHttps)
   at RiotSharp.RiotApi.GetSummoner(Region region, String summonerName)
   at Bot.Form1.button1_Click(Object sender, EventArgs e) in D:\Desktop\GetHeard\Bot\Bot\Form1.cs:line 27
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'eune.api.pvp.net'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---<---

Hope you could help me,

Thanks
Sking3000

**Comment by MingweiSamuel** [comment]
the host should be `eun1.api.riotgames.com`, not sure why its using the wrong one

**Comment by JanOuborny** [comment]
2.5.6 is outdated. To use RiotSharp right now, you have to use the latest build of the develop branch.

**Comment by dgraney** [comment]
I am 10 days late to this, however @Sking3000  , just a note that you could use 
`var summoner = api.GetSummonerByName(RiotSharp.Region.eune, "SummonerName")`
This is shown under the README.md

**Comment by JanOuborny** [comment]
See #456 and #445 for more information. Closing, feel free to reopen it if you have any questions.
