### ISSUE TITLE
RiotSharp Dependency issue?

### ISSUE THREAD

**Issue by creepercats** [BenFradet/RiotSharp#484]
So i downloaded the riotsharp Zip file and built the Riotsharp project. Then went to my project and added the bult .dll file too my project. But when i try to GetDevelopmentInstance("API_KEY") i get this error.

System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=RiotSharp
  StackTrace:
   at RiotSharp.Http.RequesterBase..ctor(String apiKey)
   at RiotSharp.RiotApi.GetInstance(String apiKey, IDictionary`2 rateLimits)
   at RiotSharp.RiotApi.GetDevelopmentInstance(String apiKey, Int32 rateLimitPer1s, Int32 rateLimitPer2m)
   at LeagueAnilyst.Form1..ctor() in c:\users\creepercats\documents\visual studio 2017\Projects\LeagueAnilyst\LeagueAnilyst\Form1.cs:line 16
   at LeagueAnilyst.Program.Main() in c:\users\creepercats\documents\visual studio 2017\Projects\LeagueAnilyst\LeagueAnilyst\Program.cs:line 19

Thanks in advance!

**Comment by creepercats** [comment]
NVM i got this working my doing the following.

1. Make a new project.
2. Change target net platform to 4.6.1
3. Updating Newtonsoft
4. Updating System.Net.Http
