### ISSUE TITLE
GetRecentGames return an error

### ISSUE THREAD

**Issue by Belterius** [BenFradet/RiotSharp#495]
When using GetRecentGames(RiotSharp.Misc.Region.euw, correctSummonerID) on a {RiotSharp.SummonerEndpoint.Summoner} I get an error {"403, Forbidden"}

When using GetRecentMatches(RiotSharp.Misc.Region.euw, correctSummonerID) on a {RiotSharp.RiotApi} I get an error {"404, Resource not found"}

I am not sure what is causing the issue, the StackTrace looks like that when calling from {RiotSharp.RiotApi} :

   at RiotSharp.Http.RequesterBase.HandleRequestFailure(HttpStatusCode statusCode)
   at RiotSharp.Http.RequesterBase.Get(HttpRequestMessage request)
   at RiotSharp.Http.RateLimitedRequester.CreateGetRequest(String relativeUrl, Region region, List`1 addedArguments, Boolean useHttps)
   at RiotSharp.RiotApi.GetRecentMatches(Region region, Int64 accountId)
   at projectName.Model.Student.GetLastMatchesFromSummoner(Region region, Int64 summonnerID)

And is quite similar when calling from {RiotSharp.SummonerEndpoint.Summoner} :
 at RiotSharp.Http.RequesterBase.HandleRequestFailure(HttpStatusCode statusCode)
   at RiotSharp.Http.RequesterBase.Get(HttpRequestMessage request)
   at RiotSharp.Http.RateLimitedRequester.CreateGetRequest(String relativeUrl, Region region, List`1 addedArguments, Boolean useHttps)
   at RiotSharp.SummonerEndpoint.SummonerBase.GetRecentGames()
   at projectName.Model.Student.GetLastMatchesFromSummoner(Region region, Int64 summonnerID)

**Comment by JanOuborny** [comment]
Are you using the latest version 3.0.1?

**Comment by Belterius** [comment]
Yes, Latest stable 3.0.1 (Installed with NuGet)

**Comment by Talha-T** [comment]
Are you sure your key is valid?

**Comment by FenrirTheKnight** [comment]
Hello, I'm currently experiencing the exact same issue with the following methods : 

GetRecentGames(RiotSharp.Misc.Region.euw, mySummonerId) on a {RiotSharp.SummonerEndpoint.Summoner} => 403 forbidden

GetRecentMatches(RiotSharp.Misc.Region.euw, mySummonerId) on a {RiotSharp.RiotApi} => 404, Resource not found 

GetMatchList(RiotSharp.Misc.Region.euw, mySummonerId) on a {RiotSharp.RiotApi} => 404, Resource not found

I'm using 3.0.1 from NuGet as well, I am fairly certain my API Key is valid, resetted it 3 times to be sure. I've been trying to find a workaround, without success for the moment. I'll post here if I find one, but does anyone have any idea what's off with these methods for now ?

**Comment by JanOuborny** [comment]
As far as I know the `GetRecentGames` no longer exists, except on the SummonerBase, which is deprecated.

However, I think your issue is that you are using a summoner id instead of an account id. I also get a 403 error if I try to use the endpoint with a summoner id, but with an account id it works.

Example:
https://euw1.api.riotgames.com/lol/match/v3/matchlists/by-account/201104942/recent returns 200
https://euw1.api.riotgames.com/lol/match/v3/matchlists/by-account/42218540/recent returns 403 or 404

**Comment by FenrirTheKnight** [comment]
Oh my, you are right ! Thank you very much for getting rid of my confusion on that topic :)
