### ISSUE TITLE
Error setting value to 'PlatformId' on 'RiotSharp.Endpoints.MatchEndpoint.Player'.

### ISSUE THREAD

**Issue by adfinlay** [BenFradet/RiotSharp#592]
I'm struggling to work out what is causing this, but it seems that there is an issue when deserializing `Player`s that are bots. I can consistently reproduce this from my own project for game 3845349278 in EUW (`RiotApi.Match.GetMatchAsync`), but when running the `GetMatchAsync_Test` it deserializes just fine. 

I have matched the Newtonsoft.Json versions (11.0.2) to make sure that wasn't the cause.

The trace is:
```
Newtonsoft.Json.JsonSerializationException : Error setting value to 'PlatformId' on 'RiotSharp.Endpoints.MatchEndpoint.Player'.
  ----> System.NullReferenceException : Object reference not set to an instance of an object.
   at Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at RiotSharp.Endpoints.MatchEndpoint.MatchEndpoint.<GetMatchAsync>d__15.MoveNext()
```

**Comment by BenFradet** [comment]
What I would do in this case is make the request without RiotSharp (using postman or something like that) and look at the platform value.

Most likely it's a platform that is not handled by either:

- [PlatformConverter](https://github.com/BenFradet/RiotSharp/blob/master/RiotSharp/Misc/Converters/PlatformConverter.cs), or
- [Platform](https://github.com/BenFradet/RiotSharp/blob/master/RiotSharp/Misc/Platform.cs), or
- the field is not named `PlatformId` but something else which seems unlikely since you said the test passes

**Comment by adfinlay** [comment]
The bot participant identity in the API response contains the following:
```
        {
            "player": {
                "currentPlatformId": "EUW1",
                "summonerName": "Ashe",
                "matchHistoryUri": "/v1/stats/player_history//0",
                "platformId": "",
                "currentAccountId": 0,
                "profileIcon": 0,
                "accountId": 0
            },
            "participantId": 6
        }
```
It's likely the blank `platformId` that is causing the issue, but I don't understand why the test passes, meaning it can successfully deserialize the response.

It's also a bit confusing that it's a NullReferenceException - that would make me think that the issue is that the `Player` object is null when trying to set the `platformId` as I think the converter is working in this regard.

**Comment by BenFradet** [comment]
the test most likely doesn't have bots, I'd suggest adding a `NoPlatform` for the empty string

**Comment by adfinlay** [comment]
Sorry, I meant to clarify that I changed the game ID that the test uses to be the one I am using to reproduce the issue.

**Comment by BenFradet** [comment]
Ah ok, then can you show the code you're using and the tests you're running (if you've made any modifications)?

**Comment by adfinlay** [comment]
I can reproduce this in my codebase with the following unit test:
```
[Explicit]
[Test]
public async Task GetLolMatchDataDirect()
{
    const long gameId = 3845349278;
    const Region region = Region.euw;
    const string riotApiKey = "...";

    var api = RiotApi.GetDevelopmentInstance(riotApiKey);

    var matchData = await api.Match.GetMatchAsync(region, gameId).ConfigureAwait(false);

    Assert.IsNotNull(matchData);
}
```

As I mentioned, running https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp.Test/RiotApiTest.cs#L121 and just changing the `GetMatchAsync` arguments to be the ones I'm testing passes but the code is virtually identical, and the only difference is that in one case I'm running the test from within your codebase and in the other I'm including the build dll... 😕

**Comment by adfinlay** [comment]
So I ended up getting down adn dirty with debugging the Newtonsoft.Json code as the match object was being deserialized and it seems the difference in behaviour comes from the fact that my project that includes RiotSharp is targeted at .NET 4.7.2. 

This means that `System.Security.Permissions` is available, and therefore https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonTypeReflector.cs#L465 returns `true` for `JsonTypeReflector.DynamicCodeGeneration`. This leads to a `DynamoicValueProvider` being used to set the value of `PlatformId` which doesn't handle `null`. 

When debugging directly in your codebase it is targeting .NET Core, and this leads to an `ExpressionValueProvider` being used, which handles `null` and sets the value to the default (`Platform.NA1`).

I'm not sure of the best way to approach fixing/working around this though. Would you still recommend 
```
I'd suggest adding a NoPlatform for the empty string
```
? If so I'll submit a PR.

**Comment by BenFradet** [comment]
yes I think `NoPlatform` is more appropriate than defaulting to NA esp if we're talking bots, wdyt @JanOuborny ?

**Comment by JanOuborny** [comment]
@BenFradet I agree. 👍
