### ISSUE TITLE
Cache throws ArgumentOutOfRangeException exception

### ISSUE THREAD

**Issue by JanOuborny** [BenFradet/RiotSharp#666]
```
 ---> System.ArgumentOutOfRangeException: Time-out interval must be less than 2^32-2. (Parameter 'dueTime')
   at System.Threading.Timer..ctor(TimerCallback callback, Object state, TimeSpan dueTime, TimeSpan period)
   at RiotSharp.Caching.Cache.StartObserving[TK](TK key, TimeSpan timeSpan)
   at RiotSharp.Caching.Cache.Add[TK,TV](TK key, TV value, TimeSpan timeSpan, Boolean isSliding)
   at RiotSharp.Caching.Cache.Add[TK,TV](TK key, TV value, TimeSpan slidingExpiry)
   at RiotSharp.Endpoints.MatchEndpoint.MatchEndpoint.GetMatchTimelineAsync(Region region, Int64 matchId)
```

**Comment by Rezga12** [comment]
I couldn't reproduce the bug, but after some static analysis I caught on next cases:

An Exception is thrown by **Ststem.Threading.Timer** constructor and it says that parameter named **'dueTIme'** is greater than 2^32 (I.E. integer upper limit). 

The Actual value passed to this Constructor is **MatchEndpoint,MatchTtl**  which is defined as:
```C#
private static readonly TimeSpan MatchTtl = TimeSpan.FromDays(60);
```
**60** days are **5 billion** Milliseconds that's greater than **2^32**(about 2 billion) MS.

I think reducing the match TTL in cache might help.
